version: "3.9"

services:
  prod:
    build:
      context: .
      target: prod
    container_name: frontend_prod
    ports:
      - "80:80"
  dev:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    container_name: frontend_dev